### ISSUE TITLE
failure in 3.14.0b4

### ISSUE THREAD

**Issue by replabrobin** [dougmercer/signified#41]
I get an error running the trivial example in 3.14.0b4

`
(314) robin@minikat:~/tmp/314
$ python
Python 3.14.0b4 (main, Jul  8 2025, 23:44:20) [GCC 15.1.1 20250425] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from signified import Signal
>>> n = Signal(3)
>>> nsq = n ** 2
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    nsq = n ** 2
          ~~^^~~
  File "/home/robin/tmp/314/lib/python3.14/site-packages/signified/ops.py", line 777, in __pow__
    return computed(f)(self, other)
           ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/robin/tmp/314/lib/python3.14/site-packages/signified/utils.py", line 72, in wrapper
    return Computed(compute_func, (*args, *kwargs.values()))
  File "/home/robin/tmp/314/lib/python3.14/site-packages/signified/core.py", line 226, in __init__
    self.notify()
    ~~~~~~~~~~~^^
  File "/home/robin/tmp/314/lib/python3.14/site-packages/signified/core.py", line 120, in notify
    for observer in self._observers:
                    ^^^^^^^^^^^^^^^
  File "/home/robin/LOCAL/3.14.0b4/lib/python3.14/_weakrefset.py", line 25, in __iter__
    for itemref in self.data.copy():
                   ^^^^^^^^^^^^^^
AttributeError: 'OrderedSet' object has no attribute 'copy'
>>> 
`

**Comment by dougmercer** [comment]
Fixed in #43 -- still not quite sure why python3.14 breaks this, but oh well

Just published a new release to pypi -- 0.2.6 should work with 3.14
